# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - python3.11 --version
      - python3.11 file.py
      - pipx run --python python3.11 --spec=black==23.3.0 black --target-version py311 --diff file.py
      - "pipx run --python python3.11 --spec=black==23.7.0 black --target-version py311 --diff file.py || :"
